#include <stdio.h>
#include <stdlib.h>
#include <ctype.h> 
#include <stdbool.h>
#include <string.h>
#include "build.h"
#include "findfiles.h"
#include <sys/stat.h>
#include "words.h"
#include "trovefile.h"
